# vim ft=yaml
# Build pyside wheels for the travis worker
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install:
    - WHEELHOUSE=$PWD/wheelhouse
    - mkdir $WHEELHOUSE
    - PYSIDE_VERSION=1.2.2
    - PYSIDE_DIR=PySide-${PYSIDE_VERSION}
    - PYSIDE_TGZ=PySide-${PYSIDE_VERSION}.tar.gz
    - pip install wheel
    # PySide dependencies from http://pyside.readthedocs.org/en/latest/building/linux.html
    # Excluding libphonon-dev qtmobility-dev because the might not be useful
    # on travis
    - sudo apt-get install cmake libqt4-dev libxml2-dev libxslt1-dev
    - curl -O https://pypi.python.org/packages/source/P/PySide/${PYSIDE_TGZ}
    - tar xf $PYSIDE_TGZ
    - patch -p0 < cmake_python.patch
    - cd $PYSIDE_DIR
    - python setup.py bdist_wheel
    - cp dist/*.whl $WHEELHOUSE
    - cp pyside_postinstall.py $WHEELHOUSE
    - echo $WHEELHOUSE
    - ls $WHEELHOUSE
    - cd ..
script:
    - pip install -v -f $WHEELHOUSE --no-index pyside
    # Post install needed for pyside wheel
    - python $WHEELHOUSE/pyside_postinstall.py -install
    # Smoke test
    - python -c "from PySide.QtGui import *"
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "PGc66yxRIZoEze+KNhHHsd++tCkWKPdzWQbIrBSL0rO68Q0yb8lAmYjr2jEaqfXdpym5yk6wGgxZoO9dEkvSJGzNe3UeFyaXMpiqBNbVkUD0xxyL8pgsHVf7LpTC1O/drEAKad14MKFMKgno5c0cD8BSyEX2EsuraBBmCwhbkhg="
  region: ORD
  container: wheels
  skip_cleanup: true
